### ISSUE TITLE
question: does inlay expr text rendering support any/all debug adapters?

### ISSUE THREAD

**Issue by phrohdoh** [hediet/vscode-realtime-debugging#13]
The readme states the following:

> Shows the text that was written to stdout next to the statement.

But I am not seeing this, only seeing it written to the debug console.

Is there anything particular I might need to do for non-JS/TS?

**Comment by hediet** [comment]
> Theoretically supports every debugger and language out there (there is nothing in the implementation specific to JavaScript).

It depends on the debug adapter. If it does not work out of the box, I guess in your case the lldb debug adapter does not seem to report the source of log outputs.

**Comment by hediet** [comment]
[You could install this extension](https://marketplace.visualstudio.com/items?itemName=hediet.hediet-power-tools) and have a look at the DAP log output and see whether there are some interesting events that could help. But I doubt it, there is not much to configure.

Also, I guess, this feature can only really be supported by debug adapters that are specific to a language, since they need to trace back the stdout data to the method invocation.

**Comment by phrohdoh** [comment]
> this feature can only really be supported by debug adapters that are specific to a language, since they need to trace back the stdout data to the method invocation.

I see.  Unfortunate for my current case, but oh well.

Thanks for the quick responses!
